name: TSU Pod 153

on:
  pull_request:
    branches: [ "main" ]

jobs:
  by-doing:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 01 - Intro to Python
        working-directory: ./by-doing/s01_intro
        run: |
          python 04_variables_and_printing.py
          python 06_numbers.py
          python 10_strings.py
          python 11_string_formatting.py
          python 12_getting_user_input.py
          python 14_booleans_and_comparisons.py
          python 15_and_&_or.py
          python 16_lists.py